# Generated by Django 3.0.5 on 2020-05-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dinnerplatters_pasta_salads_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
