# Generated by Django 3.0.5 on 2020-05-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('main', models.CharField(max_length=64)),
                ('item', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
