# Generated by Django 3.0.5 on 2020-05-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='toppings',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
