# Generated by Django 3.0.5 on 2020-05-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orders_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='username',
        ),
    ]
